import './globals.css'

export const metadata = {
  title: 'Dev EMEKA',
  description: 'Generated by DEV emeka',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative h-fit">{children}</body>
    </html>
  )
}
